# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1604-desktop"
  
  config.vm.network :forwarded_port, guest: 22, host: 22
  config.vm.network :forwarded_port, guest: 22, host: 2219
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
